services:
  - type: web
    name: crop-recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ml_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0